name: "wheelspin_coins_rewards"
description: "A description of your project"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  flutter_modular: ^5.0.3
  mockito: ^5.4.0
  flutter_hooks: ^0.18.6
  quiver: ^3.2.1
  ui_lib:
    git:
      url: git@github.com:discovery-ltd/v1-ui-lib-flutter.git
      path: ui_lib
      ref: 0.0.3-b19
  game_orchestration_micro_service_sdk:
    git:
      url: git@github.com:discovery-ltd/v1-game-orchestration-micro-service-sdk-flutter.git
      path: game_orchestration_micro_service_sdk
  manage_game_micro_service_sdk:
    git:
      url: git@github.com:discovery-ltd/v1-manage-game-micro-service-sdk-flutter.git        
      path: manage_game_micro_service_sdk
  framework_contracts_flutter:
    git:
      url: git@github.com:discovery-ltd/v1-framework-contracts-flutter.git
      path: framework_contracts_flutter
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.2

flutter:
