name: test_app
description: "Test app for wheelspin_coins_rewards Widget"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_hooks: ^0.18.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  html: ^0.15.0
  cookie_jar: ^4.0.5
  wheelspin_coins_rewards:  
    path: ../wheelspin_coins_rewards

  ui_lib:
    git:
      url: git@github.com:discovery-ltd/v1-ui-lib-flutter.git
      path: ui_lib
      ref: 0.0.3-b19

  game_orchestration_micro_service_sdk:
    git:
      url: git@github.com:discovery-ltd/v1-game-orchestration-micro-service-sdk-flutter.git
      path: game_orchestration_micro_service_sdk    
  manage_game_micro_service_sdk:
    git:
      url: git@github.com:discovery-ltd/v1-manage-game-micro-service-sdk-flutter.git        
      path: manage_game_micro_service_sdk      
      
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/